import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut, updateProfile } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getFirestore, collection, deleteDoc, doc, getDoc, onSnapshot, serverTimestamp, setDoc } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.111.0";

const firebaseConfig = {apiKey:"AIzaSyDBMMKFmaszQIr1ew1bYKmZh43wRREiBtU",authDomain:"ginescloset-12beb.firebaseapp.com",projectId:"ginescloset-12beb",storageBucket:"ginescloset-12beb.firebasestorage.app",messagingSenderId:"573851675742",appId:"1:573851675742:web:3a02ad99df18697cf1d8cf"};
const SUPABASE_URL = "https://daajdymciembtrcjwwad.supabase.co";
const SUPABASE_KEY = "sb_publishable_fch-mECSrCp72slTlIRsrw_FunRRKCU";
const firebaseApp = initializeApp(firebaseConfig);
const auth = getAuth(firebaseApp);
const db = getFirestore(firebaseApp);
const supabase = createClient(SUPABASE_URL,SUPABASE_KEY,{accessToken:async()=>auth.currentUser?auth.currentUser.getIdToken(false):null});

const BRANDS = ["Louis Vuitton","Dior","Gucci","Prada","Balenciaga","Versace","Dolce & Gabbana","Fendi","Burberry","Givenchy","Saint Laurent (YSL)","Loewe","Celine","Valentino","Hermès","Chanel","Miu Miu","Maison Margiela","Alexander McQueen","Moncler","Stone Island","Palm Angels","Amiri","Off-White","Fear of God","Supreme","Chrome Hearts","Gallery Dept.","Rhude","Denim Tears","Essentials","Corteiz","Trapstar","Nike","Jordan","Adidas","New Balance","Cartier","Kenzo","Alo","Bottega Desires","Nude Project","Purple"];
const CATEGORIES = [["camisetas","Camisetas","CM"],["sudaderas","Sudaderas","SD"],["polos","Polos","PO"],["camisetas-futbol","Camisetas de fútbol","CF"],["abrigos","Abrigos","AB"],["zapatos","Zapatos","ZP"],["pantalones-cortos","Pantalones cortos","PC"],["pantalones-largos","Pantalones largos","PL"],["bolsos","Bolsos","BO"],["carteras","Carteras","CR"],["rinoneras","Riñoneras","RN"]];
const CATEGORY_LABELS = Object.fromEntries(CATEGORIES.map(item=>[item[0],item[1]]));
const SINGLE_SIZE_CATEGORIES = new Set(["bolsos","carteras","rinoneras"]);
const LEGACY_CATEGORIES = {vestidos:"camisetas",tops:"camisetas",conjuntos:"sudaderas",chaquetas:"abrigos",calzado:"zapatos",pantalones:"pantalones-largos",rinonera:"rinoneras",cartera:"carteras",bolso:"bolsos"};
const SIZE_GROUPS = [
  {id:"adult-clothes",kind:"ADULTO",label:"Ropa de adulto",hint:"Tallas internacionales",sizes:["XS","S","M","L","XL","XXL"]},
  {id:"kids-clothes",kind:"INFANTIL",label:"Camisetas y ropa infantil",hint:"Desde bebé hasta 16 años",sizes:["0-3 meses","3-6 meses","6-9 meses","9-12 meses","12-18 meses","18-24 meses","2 años","3 años","4 años","5 años","6 años","8 años","10 años","12 años","14 años","16 años"]},
  {id:"kids-shoes",kind:"INFANTIL",label:"Calzado infantil",hint:"Numeración europea del 16 al 35",sizes:["16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35"]},
  {id:"adult-shoes",kind:"ADULTO",label:"Calzado de adulto",hint:"Numeración europea",sizes:["36","37","38","39","40","41","42","43","44","45"]},
  {id:"single-size",kind:"ÚNICA",label:"Talla única",hint:"Accesorios y complementos",sizes:["Única"]}
];
const PRODUCT_CACHE_KEY = "gc_catalog_cache_v2";
const AUTH_HINT_KEY = "gc_auth_hint_v1";
const cachedProducts = readProductCache();

const state = {user:null,profile:{},role:"customer",products:cachedProducts||[],productSignature:cachedProducts?productSignature(cachedProducts):"",productsReady:cachedProducts!==null,requests:[],ready:false,view:"catalog",editId:"",search:"",category:"all",status:"all",requestSearch:"",requestStatus:"all",media:[],removedPaths:[],dirty:false,autosaveTimer:null,stopProducts:null,stopRequests:null};
const root = document.querySelector("#adminMain");
const esc = (value="") => String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const norm = value => String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
function publicAsset(value){return String(value||"").replace(/^media\//,"");}
function productImages(product){const list=Array.isArray(product.images)?product.images.map(item=>publicAsset(typeof item==="string"?item:item?.url)).filter(Boolean):[];return list.length?list:[publicAsset(product.image)||"producto-1.jpg"];}
function productPaths(product){const list=Array.isArray(product.storagePaths)?product.storagePaths.filter(Boolean):[];return list.length?list:(product.storagePath?[product.storagePath]:[]);}
function normalizeProduct(product){return {...product,id:String(product.id||""),category:LEGACY_CATEGORIES[product.category]||product.category||"camisetas",sizes:Array.isArray(product.sizes)?product.sizes:[],images:productImages(product),storagePaths:productPaths(product),image:productImages(product)[0],active:product.active!==false};}
function productSignature(products){return JSON.stringify(products.map(product=>[product.id,product.name,product.brand,product.category,product.price,product.image,product.badge,product.sizes,product.active,product.createdOrder]));}
function readProductCache(){try{const parsed=JSON.parse(sessionStorage.getItem(PRODUCT_CACHE_KEY)||"null");return Array.isArray(parsed)?parsed.map(normalizeProduct):null;}catch{return null;}}
function writeProductCache(products){try{sessionStorage.setItem(PRODUCT_CACHE_KEY,JSON.stringify(products));}catch{/* El gestor continúa sin caché. */}}
function price(value){const raw=String(value??"").trim();if(!raw||norm(raw)==="consultar")return"Consultar";const number=Number(raw.replace(/\./g,"").replace(",","."));return Number.isFinite(number)?new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(number):raw;}
function initials(brand){return brand.split(/[\s&()-]+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase();}
function validProductPrice(value){const raw=String(value??"").trim();if(!raw||norm(raw)==="consultar")return true;const cleaned=raw.replace(/[^\d.,-]/g,"");if(!cleaned)return false;const normalized=cleaned.includes(",")?cleaned.replace(/\./g,"").replace(",", "."):cleaned;const number=Number(normalized);return Number.isFinite(number)&&number>=0;}
function firestoreAdminMessage(error,fallback="No se ha podido guardar el cambio."){const code=String(error?.code||"").toLowerCase(),message=String(error?.message||"").toLowerCase();if(code.includes("permission-denied")||message.includes("permission"))return"Firebase ha bloqueado el cambio. Publica el archivo firestore.rules incluido con la web y vuelve a iniciar sesión.";if(code.includes("unavailable")||message.includes("offline")||message.includes("network"))return"No hay conexión con Firebase. Comprueba Internet e inténtalo de nuevo.";return fallback;}

function setActiveNav(view){document.querySelectorAll("[data-admin-view]").forEach(button=>button.classList.toggle("active",button.dataset.adminView===view));document.body.classList.remove("admin-menu-open");}
function goTo(view,id=""){
  if(state.dirty&&state.view==="editor"&&view!=="editor"&&!confirm("Tienes cambios sin guardar. ¿Quieres salir del editor?"))return;
  state.view=view;state.editId=id;state.dirty=false;setActiveNav(view);render();root.focus();
}
function render(){if(!state.ready)return;if(state.role!=="admin"){renderDenied();return;}if(state.view==="editor")renderEditor();else if(state.view==="profile")renderProfile();else if(state.view==="requests")renderRequests();else if(!state.productsReady)renderCatalogLoading();else renderCatalog();updatePendingRequestCount();}

function renderCatalogLoading(){root.innerHTML=`<div class="admin-main-shell"><header class="admin-page-head"><div><p class="kicker">GESTIÓN DE CATÁLOGO</p><h1>Mis artículos</h1><span>Sincronizando el catálogo…</span></div></header><div class="admin-loading-list" aria-label="Cargando catálogo">${Array.from({length:5},()=>'<div><i></i><span></span><b></b></div>').join("")}</div></div>`;}

function renderDenied(){root.innerHTML=`<div class="admin-main-shell"><div class="admin-empty"><span>!</span><h2>Esta cuenta no es administradora</h2><p>Has iniciado sesión como ${esc(state.user?.email||"cliente")}. Solo la cuenta con role = admin puede entrar aquí.</p><div><a class="button button-secondary" href="index.html">Volver a la tienda</a> <button class="button button-primary" id="deniedLogout" type="button">Usar otra cuenta</button></div></div></div>`;root.querySelector("#deniedLogout")?.addEventListener("click",logoutNow);}

function filteredProducts(){const term=norm(state.search);return state.products.filter(product=>{const match=!term||norm([product.name,product.brand,CATEGORY_LABELS[product.category],product.description].join(" ")).includes(term);return match&&(state.category==="all"||product.category===state.category)&&(state.status==="all"||(state.status==="published"?product.active:!product.active));});}
function renderCatalog(){
  const products=filteredProducts();
  root.innerHTML=`<div class="admin-main-shell"><header class="admin-page-head"><div><p class="kicker">GESTIÓN DE CATÁLOGO</p><h1>Mis artículos</h1><span>${state.products.length} artículo${state.products.length===1?"":"s"} en el catálogo</span></div><div class="admin-head-actions"><a class="admin-secondary-link" href="catalogo.html" target="_blank" rel="noopener">Ver tienda ↗</a><button class="button button-primary" id="newProduct" type="button">＋ Nuevo artículo</button></div></header>
    <div class="admin-toolbar"><label class="admin-search"><span>⌕</span><input id="adminSearch" type="search" value="${esc(state.search)}" placeholder="Buscar artículos, marcas o categorías"></label><select id="adminCategory"><option value="all">Todas las categorías</option>${CATEGORIES.map(item=>`<option value="${item[0]}" ${state.category===item[0]?"selected":""}>${esc(item[1])}</option>`).join("")}</select><select id="adminStatus"><option value="all">Todos los estados</option><option value="published" ${state.status==="published"?"selected":""}>Publicados</option><option value="draft" ${state.status==="draft"?"selected":""}>Borradores</option></select></div>
    ${products.length?`<div class="admin-product-list">${products.map(productRow).join("")}</div>`:`<div class="admin-empty"><span>◇</span><h2>${state.products.length?"No hay coincidencias":"Tu catálogo está preparado"}</h2><p>${state.products.length?"Prueba con otra búsqueda o cambia los filtros.":"Añade el primer artículo para empezar."}</p><button class="button button-primary" id="emptyNewProduct" type="button">＋ Nuevo artículo</button></div>`}</div>`;
  bindCatalog();
}
function productRow(product){return `<article class="admin-product-row"><img src="${esc(product.image)}" alt="${esc(product.name)}" onerror="this.src='producto-1.jpg'"><div><h3>${esc(product.name)}</h3><p>${esc(product.brand||"GinesCloset")}</p></div><small>${esc(CATEGORY_LABELS[product.category]||product.category)}</small><small>${product.sizes.length?esc(product.sizes.join(", ")):"Talla única"}</small><strong>${esc(price(product.price))}</strong><span class="status-pill ${product.active?"published":"draft"}">${product.active?"Publicado":"Borrador"}</span><div class="row-actions"><button data-edit="${esc(product.id)}" type="button">Editar</button><div class="more-menu"><button data-more="${esc(product.id)}" type="button" aria-label="Más acciones">•••</button><div class="more-popover hidden" data-menu="${esc(product.id)}"><button data-duplicate="${esc(product.id)}" type="button">Duplicar</button><button class="danger" data-delete="${esc(product.id)}" type="button">Eliminar</button></div></div></div></article>`;}
function bindCatalog(){
  root.querySelector("#newProduct")?.addEventListener("click",()=>goTo("editor"));root.querySelector("#emptyNewProduct")?.addEventListener("click",()=>goTo("editor"));
  root.querySelector("#adminSearch")?.addEventListener("input",event=>{state.search=event.target.value;clearTimeout(renderCatalog.timer);renderCatalog.timer=setTimeout(()=>{renderCatalog();const next=root.querySelector("#adminSearch");next?.focus();next?.setSelectionRange(next.value.length,next.value.length);},140);});
  root.querySelector("#adminCategory")?.addEventListener("change",event=>{state.category=event.target.value;renderCatalog();});root.querySelector("#adminStatus")?.addEventListener("change",event=>{state.status=event.target.value;renderCatalog();});
  root.querySelectorAll("[data-edit]").forEach(button=>button.addEventListener("click",()=>goTo("editor",button.dataset.edit)));
  root.querySelectorAll("[data-more]").forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();const menu=root.querySelector(`[data-menu="${CSS.escape(button.dataset.more)}"]`);root.querySelectorAll(".more-popover").forEach(item=>{if(item!==menu)item.classList.add("hidden")});menu.classList.toggle("hidden");}));
  root.querySelectorAll("[data-duplicate]").forEach(button=>button.addEventListener("click",()=>duplicateProduct(button.dataset.duplicate)));
  root.querySelectorAll("[data-delete]").forEach(button=>button.addEventListener("click",()=>confirmDelete(button.dataset.delete)));
}

function updatePendingRequestCount(){const pending=state.requests.filter(request=>request.status==="pending").length,node=document.querySelector("#pendingRequestCount");if(node){node.textContent=pending;node.classList.toggle("hidden",!pending);}}
function requestDate(value){const date=value?.toDate?value.toDate():value?.seconds?new Date(value.seconds*1000):null;return date&&!Number.isNaN(date.getTime())?new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(date):"Ahora";}
function requestStatusLabel(status){return status==="offered"?"Oferta enviada":status==="closed"?"Cerrada":"Pendiente";}
function filteredRequests(){const term=norm(state.requestSearch);return state.requests.filter(request=>{const haystack=norm([request.requestNumber,request.clientNumber,request.customerName,request.customerEmail,request.customerPhone,...(request.items||[]).flatMap(item=>[item.name,item.brand,item.size])].join(" "));return(!term||haystack.includes(term))&&(state.requestStatus==="all"||request.status===state.requestStatus);});}
function renderRequests(){const requests=filteredRequests(),pending=state.requests.filter(request=>request.status==="pending").length;root.innerHTML=`<div class="admin-main-shell requests-shell"><header class="admin-page-head"><div><p class="kicker">ATENCIÓN AL CLIENTE</p><h1>Solicitudes</h1><span>Carritos enviados por clientes para preparar una oferta.</span></div><div class="request-summary"><b>${pending}</b><span>pendiente${pending===1?"":"s"}</span></div></header><div class="request-toolbar"><label class="admin-search"><span>⌕</span><input id="requestSearch" type="search" value="${esc(state.requestSearch)}" placeholder="Buscar cliente, número o artículo"></label><select id="requestStatus"><option value="all">Todos los estados</option><option value="pending" ${state.requestStatus==="pending"?"selected":""}>Pendientes</option><option value="offered" ${state.requestStatus==="offered"?"selected":""}>Oferta enviada</option><option value="closed" ${state.requestStatus==="closed"?"selected":""}>Cerradas</option></select></div>${requests.length?`<div class="request-list">${requests.map(requestCard).join("")}</div>`:`<div class="admin-empty"><span>◇</span><h2>No hay solicitudes</h2><p>${state.requests.length?"Cambia la búsqueda o el estado seleccionado.":"Cuando un cliente envíe su carrito aparecerá aquí."}</p></div>`}</div>`;root.querySelector("#requestSearch")?.addEventListener("input",event=>{state.requestSearch=event.target.value;clearTimeout(renderRequests.timer);renderRequests.timer=setTimeout(()=>{renderRequests();const input=root.querySelector("#requestSearch");input?.focus();input?.setSelectionRange(input.value.length,input.value.length);},140);});root.querySelector("#requestStatus")?.addEventListener("change",event=>{state.requestStatus=event.target.value;renderRequests();});root.querySelectorAll("[data-request-offer]").forEach(button=>button.addEventListener("click",()=>openOffer(button.dataset.requestOffer)));root.querySelectorAll("[data-request-close]").forEach(button=>button.addEventListener("click",()=>setRequestStatus(button.dataset.requestClose,"closed")));}
function requestCard(request){const items=Array.isArray(request.items)?request.items:[];return `<article class="request-card"><header><div><span class="request-status ${esc(request.status||"pending")}">${esc(requestStatusLabel(request.status))}</span><b>${esc(request.requestNumber||request.id)}</b><small>${esc(requestDate(request.createdAt))}</small></div><div class="request-customer"><strong>${esc(request.customerName||"Cliente")}</strong><span>${esc(request.clientNumber||"Sin número")}</span><a href="tel:${esc(request.customerPhone||"")}">${esc(request.customerPhone||"Sin teléfono")}</a></div></header><div class="request-products">${items.map(item=>`<div><img src="${esc(item.image||"producto-1.jpg")}" alt=""><span><b>${esc(item.name||"Artículo")}</b><small>${esc(item.brand||"GINESCLOSET")}${item.size?` · Talla ${esc(item.size)}`:""}</small></span><strong>${esc(price(item.price))}</strong></div>`).join("")}</div>${request.offerPrice?`<div class="request-last-offer"><span>Última oferta</span><b>${esc(request.offerPrice)}</b>${request.offerNote?`<small>${esc(request.offerNote)}</small>`:""}</div>`:""}<footer><span>${items.length} artículo${items.length===1?"":"s"}</span><div><button class="button button-secondary" data-request-close="${esc(request.id)}" type="button" ${request.status==="closed"?"disabled":""}>${request.status==="closed"?"Cerrada":"Marcar cerrada"}</button><button class="button button-primary" data-request-offer="${esc(request.id)}" type="button">Preparar oferta por WhatsApp</button></div></footer></article>`;}
function whatsappNumber(value){let digits=String(value||"").replace(/\D/g,"");if(digits.startsWith("00"))digits=digits.slice(2);if(digits.length===9)digits=`34${digits}`;return digits;}
function openOffer(id){const request=state.requests.find(item=>item.id===id);if(!request)return;const phone=whatsappNumber(request.customerPhone);if(phone.length<10){showToast("El teléfono del cliente no es válido para WhatsApp.","error");return;}const items=Array.isArray(request.items)?request.items:[];document.body.insertAdjacentHTML("beforeend",`<div class="admin-dialog-backdrop" id="offerDialog"><section class="admin-dialog offer-dialog" role="dialog" aria-modal="true"><button class="offer-close" data-dialog-cancel type="button" aria-label="Cerrar">×</button><p class="kicker">OFERTA POR WHATSAPP</p><h2>${esc(request.customerName||"Cliente")}</h2><div class="offer-client"><span>${esc(request.clientNumber||"")}</span><b>${esc(request.customerPhone||"")}</b></div><div class="offer-products">${items.map(item=>`<div><img src="${esc(item.image||"producto-1.jpg")}" alt=""><span><b>${esc(item.name||"Artículo")}</b><small>${esc(item.brand||"")}${item.size?` · ${esc(item.size)}`:""}</small></span></div>`).join("")}</div><form id="offerForm"><label>Oferta total<input name="price" required maxlength="30" value="${esc(request.offerPrice||"")}" placeholder="Ej. 180 €"></label><label>Mensaje adicional<textarea name="note" maxlength="300" placeholder="Ej. Envío incluido y entrega estimada en 48 horas">${esc(request.offerNote||"")}</textarea></label><p class="admin-error hidden" id="offerError"></p><button class="button button-primary" type="submit">Abrir WhatsApp con la oferta</button></form></section></div>`);const dialog=document.querySelector("#offerDialog");dialog.querySelector("[data-dialog-cancel]").addEventListener("click",()=>dialog.remove());dialog.querySelector("#offerForm").addEventListener("submit",event=>sendWhatsappOffer(event,request,phone,dialog));}
async function sendWhatsappOffer(event,request,phone,dialog){event.preventDefault();const form=event.currentTarget,data=new FormData(form),offerPrice=String(data.get("price")||"").trim(),offerNote=String(data.get("note")||"").trim(),button=form.querySelector('button[type="submit"]'),errorBox=form.querySelector("#offerError");if(!offerPrice){errorBox.textContent="Escribe el importe de la oferta.";errorBox.classList.remove("hidden");return;}const itemLines=(request.items||[]).map((item,index)=>`${index+1}. ${item.name}${item.brand?` · ${item.brand}`:""}${item.size?` · Talla ${item.size}`:""}`).join("\n"),message=`Hola ${request.customerName||""}, soy GinesCloset.\n\nOferta para tu solicitud ${request.requestNumber||request.id} (${request.clientNumber||"cliente"}):\n${itemLines}\n\nOferta total: ${offerPrice}${offerNote?`\n${offerNote}`:""}\n\nSi te interesa, respóndenos por aquí.`;const whatsappWindow=window.open("about:blank","_blank");button.disabled=true;button.textContent="Preparando…";try{await setDoc(doc(db,"requests",request.id),{status:"offered",offerPrice,offerNote,offeredAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});if(whatsappWindow)whatsappWindow.location.href=`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;else location.href=`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;dialog.remove();showToast("Oferta preparada en WhatsApp","success");}catch(error){console.error(error);whatsappWindow?.close();errorBox.textContent=firestoreAdminMessage(error,"No se ha podido guardar la oferta.");errorBox.classList.remove("hidden");button.disabled=false;button.textContent="Abrir WhatsApp con la oferta";}}
async function setRequestStatus(id,status){try{await setDoc(doc(db,"requests",id),{status,updatedAt:serverTimestamp()},{merge:true});showToast("Solicitud actualizada","success");}catch(error){console.error(error);showToast(firestoreAdminMessage(error,"No se ha podido actualizar la solicitud."),"error");}}

function emptyEditorModel(){return{id:"",name:"",brand:"",category:"camisetas",price:"Consultar",description:"",badge:"NUEVO",sizes:["S","M","L"],active:false,createdOrder:Date.now(),images:[],storagePaths:[]};}
function editorProduct(){return state.editId?state.products.find(item=>item.id===state.editId):null;}
function prepareMedia(product){state.media=product?productImages(product).map((url,index)=>({id:`existing-${index}`,url,path:product.storagePaths[index]||"",file:null,existing:true})) : [];state.removedPaths=[];}
function renderEditor(){
  const source=editorProduct();let product=source?{...source}:emptyEditorModel();
  if(!source){const saved=localStorage.getItem("gc_admin_draft");if(saved){try{product={...product,...JSON.parse(saved),id:""};}catch{}}}
  prepareMedia(source);state.editorDraft=product;
  root.innerHTML=`<div class="admin-main-shell"><header class="admin-page-head"><div><p class="kicker">${source?"EDITAR ARTÍCULO":"NUEVO ARTÍCULO"}</p><h1>${source?esc(source.name):"Añade una pieza"}</h1><span>${source?"Actualiza la información y guarda los cambios.":"Completa la ficha y decide cuándo publicarla."}</span></div><div class="admin-head-actions"><button class="admin-secondary-link" id="backCatalog" type="button">← Mis artículos</button></div></header>
    <form id="productForm" novalidate><div class="editor-layout"><div class="editor-form"><section class="editor-card"><div class="editor-card-head"><h2>Información del artículo</h2><span class="autosave-state" id="autosaveState">Borrador local preparado</span></div><div class="admin-field"><span>Nombre del artículo</span><input name="name" required maxlength="80" value="${esc(product.name)}" placeholder="Ej. Sudadera Logo bordado"></div><div class="admin-field-grid"><div class="admin-field"><span>Marca</span><div class="brand-combobox"><div class="brand-combobox-input"><input id="brandInput" name="brand" required autocomplete="off" value="${esc(product.brand)}" placeholder="Buscar marca"><span>⌕</span></div><div class="brand-results hidden" id="brandResults"></div></div></div><div class="admin-field"><span>Precio</span><input name="price" value="${esc(product.price)}" placeholder="Consultar o 49,95"></div></div>
      <div class="admin-field"><span>Categoría</span><input type="hidden" name="category" value="${esc(product.category)}"><div class="category-tiles" id="categoryTiles">${categoryTiles(product.category)}</div></div><div class="admin-field-grid"><div class="admin-field"><span>Tallas</span>${sizePicker(product.sizes,product.category)}</div><div class="admin-field"><span>Etiqueta</span><input name="badge" maxlength="18" value="${esc(product.badge||"")}" placeholder="NUEVO"></div></div><div class="admin-field"><span>Descripción</span><textarea name="description" maxlength="500" placeholder="Materiales, corte y detalles importantes">${esc(product.description)}</textarea></div><label class="publish-toggle"><input name="active" type="checkbox" ${product.active?"checked":""}><i></i><span><b>Publicado y visible</b><small>Si está desactivado se guardará como borrador.</small></span></label></section>
      <section class="editor-card"><div class="editor-card-head"><h2>Fotografías</h2><span class="autosave-state">Máximo 8 imágenes</span></div><label class="media-drop" id="mediaDrop"><span>⇧</span><h3>Arrastra tus fotografías aquí</h3><p>JPG, PNG o WEBP. Las optimizaremos antes de subirlas.</p><b class="button button-secondary">Seleccionar archivos</b><input id="mediaInput" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div class="media-grid" id="mediaGrid"></div><div class="upload-progress hidden" id="uploadProgress"><i></i></div></section></div>
      <aside class="editor-preview"><div class="preview-card"><p class="preview-label">VISTA PREVIA</p><div class="preview-image" id="previewImage"></div><p id="previewMeta"></p><h3 id="previewName"></h3><strong id="previewPrice"></strong><div class="preview-sizes" id="previewSizes"></div></div></aside></div>
      <div class="editor-sticky-actions"><button class="button button-secondary" id="discardEditor" type="button">Cancelar</button><div><button class="button button-secondary" data-save="draft" type="button">Guardar borrador</button><button class="button button-primary" data-save="publish" type="button">${source?"Guardar cambios":"Publicar artículo"}</button></div></div><p class="admin-error hidden" id="editorError" role="alert"></p></form></div>`;
  bindEditor();renderMedia();updatePreview();
}
function categoryTiles(selected){return CATEGORIES.map(item=>`<button class="category-tile ${selected===item[0]?"selected":""}" data-category-value="${item[0]}" type="button"><i>${item[2]}</i><span>${esc(item[1])}</span></button>`).join("");}
function sizePicker(selected=[],category="camisetas"){return `<div class="size-dropdown"><button class="size-trigger" id="sizeTrigger" type="button" aria-expanded="false" aria-controls="sizeMenu"><span class="size-chips" id="sizeChips">${selected.length?selected.map(size=>`<i class="size-chip">${esc(size)}</i>`).join(""):"Seleccionar tallas"}</span></button><div class="size-menu hidden" id="sizeMenu" data-size-category="${esc(category)}">${SIZE_GROUPS.map(group=>`<section class="size-group" data-size-group="${group.id}"><header><div><b>${esc(group.label)}</b><small>${esc(group.hint)}</small></div><span>${esc(group.kind)} · ${group.sizes.length}</span></header><div class="size-group-grid">${group.sizes.map(size=>`<label class="size-option"><input type="checkbox" name="sizes" value="${esc(size)}" ${selected.includes(size)?"checked":""}><i>✓</i><span>${esc(size)}</span></label>`).join("")}</div></section>`).join("")}</div></div>`;}
function brandResults(term,selected){const found=BRANDS.filter(brand=>norm(brand).includes(norm(term))).slice(0,15);return found.map(brand=>`<button class="${brand===selected?"selected":""}" data-brand="${esc(brand)}" type="button"><i>${esc(initials(brand))}</i><span>${esc(brand)}</span></button>`).join("")||'<p class="brand-no-results">No hay marcas con ese nombre.</p>';}

function bindEditor(){
  const form=root.querySelector("#productForm"),brandInput=form.querySelector("#brandInput"),brandRoot=form.querySelector("#brandResults");
  root.querySelector("#backCatalog").addEventListener("click",()=>goTo("catalog"));root.querySelector("#discardEditor").addEventListener("click",()=>goTo("catalog"));
  form.addEventListener("submit",event=>event.preventDefault());
  form.addEventListener("input",()=>{state.dirty=true;updatePreview();scheduleAutosave();});
  form.querySelectorAll("[data-category-value]").forEach(button=>button.addEventListener("click",()=>{const category=button.dataset.categoryValue,wasSingle=SINGLE_SIZE_CATEGORIES.has(form.elements.category.value);form.elements.category.value=category;form.querySelectorAll(".category-tile").forEach(item=>item.classList.toggle("selected",item===button));form.querySelector("#sizeMenu").dataset.sizeCategory=category;if(SINGLE_SIZE_CATEGORIES.has(category))form.querySelectorAll('#sizeMenu input').forEach(input=>input.checked=input.value==="Única");else if(wasSingle)form.querySelectorAll('#sizeMenu input').forEach(input=>input.checked=false);renderSizeChips();state.dirty=true;updatePreview();scheduleAutosave();}));
  brandInput.addEventListener("focus",()=>{brandRoot.innerHTML=brandResults(brandInput.value,brandInput.value);brandRoot.classList.remove("hidden");bindBrandChoices();});
  brandInput.addEventListener("input",()=>{brandRoot.innerHTML=brandResults(brandInput.value,brandInput.value);brandRoot.classList.remove("hidden");bindBrandChoices();});
  function bindBrandChoices(){brandRoot.querySelectorAll("[data-brand]").forEach(button=>button.addEventListener("click",()=>{brandInput.value=button.dataset.brand;brandRoot.classList.add("hidden");state.dirty=true;updatePreview();scheduleAutosave();}));}
  form.querySelector("#sizeTrigger").addEventListener("click",event=>{const menu=form.querySelector("#sizeMenu"),open=menu.classList.toggle("hidden")===false;event.currentTarget.setAttribute("aria-expanded",String(open));});
  form.querySelectorAll('#sizeMenu input').forEach(input=>input.addEventListener("change",()=>{renderSizeChips();state.dirty=true;updatePreview();scheduleAutosave();}));
  const input=form.querySelector("#mediaInput"),drop=form.querySelector("#mediaDrop");input.addEventListener("change",()=>addMediaFiles(input.files));drop.addEventListener("dragover",event=>{event.preventDefault();drop.classList.add("dragover")});drop.addEventListener("dragleave",()=>drop.classList.remove("dragover"));drop.addEventListener("drop",event=>{event.preventDefault();drop.classList.remove("dragover");addMediaFiles(event.dataTransfer.files)});
  form.querySelectorAll("[data-save]").forEach(button=>button.addEventListener("click",()=>saveProduct(button.dataset.save)));
}
function selectedSizes(){return [...root.querySelectorAll('#sizeMenu input:checked')].map(input=>input.value);}
function renderSizeChips(){const chips=root.querySelector("#sizeChips"),selected=selectedSizes();chips.innerHTML=selected.length?selected.map(size=>`<i class="size-chip">${esc(size)}</i>`).join(""):"Seleccionar tallas";}
function draftFromForm(){const form=root.querySelector("#productForm"),data=new FormData(form),category=String(data.get("category")||"camisetas");return{name:String(data.get("name")||"").trim(),brand:String(data.get("brand")||"").trim(),category,price:String(data.get("price")||"Consultar").trim()||"Consultar",description:String(data.get("description")||"").trim(),badge:String(data.get("badge")||"").trim(),sizes:SINGLE_SIZE_CATEGORIES.has(category)?["Única"]:selectedSizes().filter(size=>size!=="Única"),active:form.elements.active.checked,createdOrder:state.editorDraft?.createdOrder||Date.now()};}
function scheduleAutosave(){clearTimeout(state.autosaveTimer);const status=root.querySelector("#autosaveState");if(status){status.textContent="Guardando borrador local…";status.classList.remove("saved");}state.autosaveTimer=setTimeout(()=>{if(!state.editId)localStorage.setItem("gc_admin_draft",JSON.stringify(draftFromForm()));if(status){status.textContent="Borrador local guardado";status.classList.add("saved");}},700);}
function updatePreview(){const product=draftFromForm(),image=state.media[0]?.url;const imageRoot=root.querySelector("#previewImage");if(imageRoot)imageRoot.innerHTML=image?`<img src="${esc(image)}" alt="Vista previa">`:'<span>◇</span>';root.querySelector("#previewMeta").textContent=`${product.brand||"Marca"} · ${CATEGORY_LABELS[product.category]||"Categoría"}`;root.querySelector("#previewName").textContent=product.name||"Nombre del artículo";root.querySelector("#previewPrice").textContent=price(product.price);root.querySelector("#previewSizes").innerHTML=product.sizes.map(size=>`<i>${esc(size)}</i>`).join("");}

async function addMediaFiles(fileList){
  const files=[...fileList].filter(file=>/^image\/(jpeg|png|webp)$/.test(file.type));if(!files.length){showToast("Selecciona fotografías JPG, PNG o WEBP.","error");return;}if(state.media.length+files.length>8){showToast("Puedes añadir un máximo de 8 fotografías.","error");return;}
  for(const file of files){try{const compressed=await compressImage(file);state.media.push({id:`new-${crypto.randomUUID()}`,url:URL.createObjectURL(compressed),file:compressed,path:"",existing:false});}catch(error){console.error(error);showToast(`No se pudo preparar ${file.name}.`,"error");}}
  state.dirty=true;renderMedia();updatePreview();
}
async function compressImage(file){
  const bitmap=await createImageBitmap(file),max=1800,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),width=Math.round(bitmap.width*scale),height=Math.round(bitmap.height*scale);const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;canvas.getContext("2d",{alpha:false}).drawImage(bitmap,0,0,width,height);bitmap.close();const blob=await new Promise((resolve,reject)=>canvas.toBlob(result=>result?resolve(result):reject(new Error("No se pudo comprimir")),"image/webp",.86));return new File([blob],`${file.name.replace(/\.[^.]+$/,"")}.webp`,{type:"image/webp"});
}
function renderMedia(){const grid=root.querySelector("#mediaGrid");if(!grid)return;grid.innerHTML=state.media.map((item,index)=>`<article class="media-item" draggable="true" data-media-index="${index}"><img src="${esc(item.url)}" alt="Fotografía ${index+1}">${index===0?'<span class="cover">PORTADA</span>':""}<div class="media-item-actions"><button data-media-cover="${index}" type="button">Portada</button><button data-media-left="${index}" type="button">←</button><button data-media-right="${index}" type="button">→</button><button class="danger" data-media-remove="${index}" type="button">×</button></div></article>`).join("");
  grid.querySelectorAll("[data-media-cover]").forEach(button=>button.addEventListener("click",()=>moveMedia(Number(button.dataset.mediaCover),0)));grid.querySelectorAll("[data-media-left]").forEach(button=>button.addEventListener("click",()=>moveMedia(Number(button.dataset.mediaLeft),Math.max(0,Number(button.dataset.mediaLeft)-1))));grid.querySelectorAll("[data-media-right]").forEach(button=>button.addEventListener("click",()=>moveMedia(Number(button.dataset.mediaRight),Math.min(state.media.length-1,Number(button.dataset.mediaRight)+1))));grid.querySelectorAll("[data-media-remove]").forEach(button=>button.addEventListener("click",()=>removeMedia(Number(button.dataset.mediaRemove))));
  let dragged=-1;grid.querySelectorAll("[data-media-index]").forEach(item=>{item.addEventListener("dragstart",()=>dragged=Number(item.dataset.mediaIndex));item.addEventListener("dragover",event=>event.preventDefault());item.addEventListener("drop",event=>{event.preventDefault();moveMedia(dragged,Number(item.dataset.mediaIndex));});});
}
function moveMedia(from,to){if(from<0||to<0||from===to)return;const[item]=state.media.splice(from,1);state.media.splice(to,0,item);state.dirty=true;renderMedia();updatePreview();}
function removeMedia(index){const[item]=state.media.splice(index,1);if(item?.existing&&item.path)state.removedPaths.push(item.path);if(item&&!item.existing)URL.revokeObjectURL(item.url);state.dirty=true;renderMedia();updatePreview();}

async function uploadMedia(item,index,total){if(item.existing)return item;const extension="webp",path=`products/${state.user.uid}/${Date.now()}-${crypto.randomUUID()}.${extension}`;updateProgress(index,total);const result=await supabase.storage.from("catalog-media").upload(path,item.file,{cacheControl:"31536000",contentType:item.file.type,upsert:false});if(result.error)throw new Error(result.error.message||"Supabase ha rechazado la fotografía.");const publicUrl=supabase.storage.from("catalog-media").getPublicUrl(path).data.publicUrl;return{...item,url:publicUrl,path,existing:true,file:null};}
function updateProgress(done,total){const box=root.querySelector("#uploadProgress"),bar=box?.querySelector("i");box?.classList.remove("hidden");if(bar)bar.style.width=`${Math.round(done/Math.max(1,total)*100)}%`;}
function storageErrorMessage(error){
  const message=String(error?.message||"").toLowerCase();
  if(message.includes("row-level")||message.includes("policy"))return"Supabase ha bloqueado la fotografía. En Supabase abre SQL Editor, ejecuta completo el archivo supabase-storage-policies.sql y vuelve a iniciar sesión.";
  if(message.includes("jwt")||message.includes("unauthorized")||message.includes("authorization"))return"Supabase no reconoce la sesión de Firebase. Activa Authentication > Third-Party Auth > Firebase con el proyecto ginescloset-12beb y vuelve a iniciar sesión.";
  return`No se ha podido subir la fotografía: ${error?.message||"error desconocido"}`;
}
async function saveProduct(mode){
  const form=root.querySelector("#productForm"),errorBox=root.querySelector("#editorError"),buttons=[...form.querySelectorAll("[data-save]")];errorBox.classList.add("hidden");const product=draftFromForm();if(mode==="publish")product.active=true;
  if(mode==="draft")product.active=false;
  if(!product.name){showEditorError("Escribe el nombre del artículo.");return;}if(!BRANDS.includes(product.brand)){showEditorError("Selecciona una marca de la lista.");return;}if(!CATEGORIES.some(item=>item[0]===product.category)){showEditorError("Selecciona una categoría.");return;}if(!validProductPrice(product.price)){showEditorError("Escribe un precio válido o utiliza “Consultar”.");return;}if(!product.sizes.length){showEditorError("Selecciona al menos una talla.");return;}if(!state.media.length){showEditorError("Añade al menos una fotografía.");return;}
  buttons.forEach(button=>button.disabled=true);const pressed=form.querySelector(`[data-save="${mode}"]`);if(pressed)pressed.textContent="Guardando…";
  const uploadedPaths=[];let stage="upload";
  try{
    const total=state.media.filter(item=>!item.existing).length;let count=0;const preparedMedia=[];for(const item of state.media){const prepared=item.existing?item:await uploadMedia(item,++count,total);preparedMedia.push(prepared);if(!item.existing)uploadedPaths.push(prepared.path);}
    updateProgress(total||1,total||1);stage="catalog";const reference=state.editId?doc(db,"products",state.editId):doc(collection(db,"products"));const images=preparedMedia.map(item=>item.url),storagePaths=preparedMedia.map(item=>item.path||"");await setDoc(reference,{...product,images,storagePaths,image:images[0],storagePath:storagePaths[0]||"",updatedAt:serverTimestamp(),createdAt:state.editId?(editorProduct()?.createdAt||serverTimestamp()):serverTimestamp()},{merge:Boolean(state.editId)});
    state.media.filter(item=>!item.existing).forEach(item=>URL.revokeObjectURL(item.url));state.media=preparedMedia;
    if(state.removedPaths.length){const removed=await supabase.storage.from("catalog-media").remove(state.removedPaths);if(removed.error)console.warn("No se pudieron limpiar algunas fotografías antiguas",removed.error);}
    localStorage.removeItem("gc_admin_draft");state.dirty=false;showToast(product.active?"Artículo publicado correctamente":"Borrador guardado","success");state.view="catalog";state.editId="";setActiveNav("catalog");renderCatalog();
  }catch(error){console.error(error);if(uploadedPaths.length)await supabase.storage.from("catalog-media").remove(uploadedPaths);showEditorError(stage==="upload"?storageErrorMessage(error):firestoreAdminMessage(error,"La fotografía se preparó, pero Firebase no pudo guardar el artículo."));buttons.forEach(button=>button.disabled=false);if(pressed)pressed.textContent=mode==="draft"?"Guardar borrador":"Publicar artículo";}
}
function showEditorError(message){const box=root.querySelector("#editorError");box.textContent=message;box.classList.remove("hidden");box.scrollIntoView({behavior:"smooth",block:"center"});}

async function duplicateProduct(id){const product=state.products.find(item=>item.id===id);if(!product)return;try{const reference=doc(collection(db,"products"));const copy={...product,name:`${product.name} (copia)`,active:false,createdOrder:Date.now(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()};delete copy.id;await setDoc(reference,copy);showToast("Artículo duplicado como borrador","success");}catch(error){console.error(error);showToast(firestoreAdminMessage(error,"No se ha podido duplicar el artículo."),"error");}}
function confirmDelete(id){const product=state.products.find(item=>item.id===id);if(!product)return;document.body.insertAdjacentHTML("beforeend",`<div class="admin-dialog-backdrop" id="deleteDialog"><section class="admin-dialog" role="dialog" aria-modal="true"><span>⌫</span><h2>¿Eliminar este artículo?</h2><p>Esta acción eliminará el artículo del catálogo. Sus fotografías de Supabase también se eliminarán.</p><div class="dialog-product"><img src="${esc(product.image)}" alt=""><b>${esc(product.name)}</b></div><div class="dialog-actions"><button data-dialog-cancel type="button">Cancelar</button><button class="danger" data-dialog-delete type="button">Eliminar definitivamente</button></div></section></div>`);const dialog=document.querySelector("#deleteDialog");dialog.querySelector("[data-dialog-cancel]").addEventListener("click",()=>dialog.remove());dialog.querySelector("[data-dialog-delete]").addEventListener("click",()=>deleteProduct(product,dialog));}
async function deleteProduct(product,dialog){const button=dialog.querySelector("[data-dialog-delete]");button.disabled=true;button.textContent="Eliminando…";try{await deleteDoc(doc(db,"products",product.id));const paths=productPaths(product);if(paths.length){const removed=await supabase.storage.from("catalog-media").remove(paths);if(removed.error)console.warn("No se pudieron limpiar las fotografías",removed.error);}dialog.remove();showToast("Artículo eliminado","success");}catch(error){console.error(error);button.disabled=false;button.textContent="Eliminar definitivamente";showToast(firestoreAdminMessage(error,"No se ha podido eliminar el artículo."),"error");}}

function renderProfile(){const name=state.profile.name||state.user.displayName||"Administrador";root.innerHTML=`<div class="admin-main-shell profile-admin-wrap"><header class="admin-page-head"><div><p class="kicker">CUENTA DE ADMINISTRACIÓN</p><h1>Mi perfil</h1><span>Consulta y actualiza tu información personal.</span></div></header><section class="admin-profile-card"><span class="role-badge">ADMINISTRADOR</span><form class="profile-form" id="adminProfileForm"><div class="field"><label>Nombre</label><input name="name" required maxlength="60" value="${esc(name)}"></div><div class="field"><label>Teléfono</label><input name="phone" type="tel" maxlength="25" value="${esc(state.profile.phone||"")}"></div><div class="field"><label>Correo electrónico</label><input value="${esc(state.user.email||"")}" disabled><span class="profile-help">El correo está protegido y no se modifica desde aquí.</span></div><p class="admin-error hidden" id="profileError"></p><button class="button button-primary" type="submit">Guardar cambios</button><button class="logout-button" id="profileLogout" type="button">Cerrar sesión</button></form></section></div>`;root.querySelector("#adminProfileForm").addEventListener("submit",saveAdminProfile);root.querySelector("#profileLogout").addEventListener("click",confirmLogout);}
async function saveAdminProfile(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=form.querySelector('button[type="submit"]'),errorBox=form.querySelector("#profileError");button.disabled=true;button.textContent="Guardando…";try{const name=String(data.get("name")).trim(),phone=String(data.get("phone")).trim();await updateProfile(state.user,{displayName:name});await setDoc(doc(db,"users",state.user.uid),{name,phone,email:(state.user.email||"").toLowerCase(),role:"admin",updatedAt:serverTimestamp()},{merge:true});state.profile={...state.profile,name,phone};showToast("Datos actualizados","success");button.disabled=false;button.textContent="Guardar cambios";}catch(error){console.error(error);errorBox.textContent=firestoreAdminMessage(error,"No se han podido guardar los cambios.");errorBox.classList.remove("hidden");button.disabled=false;button.textContent="Guardar cambios";}}
function confirmLogout(){document.body.insertAdjacentHTML("beforeend",`<div class="admin-dialog-backdrop" id="logoutDialog"><section class="admin-dialog"><span>↪</span><h2>¿Quieres cerrar la sesión?</h2><p>Volverás a la tienda pública de GinesCloset.</p><div class="dialog-actions"><button data-dialog-cancel type="button">Cancelar</button><button class="button-primary" data-dialog-logout type="button">Cerrar sesión</button></div></section></div>`);const dialog=document.querySelector("#logoutDialog");dialog.querySelector("[data-dialog-cancel]").addEventListener("click",()=>dialog.remove());dialog.querySelector("[data-dialog-logout]").addEventListener("click",logoutNow);}
async function logoutNow(){try{await signOut(auth);try{sessionStorage.setItem(AUTH_HINT_KEY,JSON.stringify({signedIn:false,role:"customer",label:"Iniciar sesión"}));}catch{}location.replace("index.html?sesion=cerrada");}catch{showToast("No se ha podido cerrar la sesión.","error");}}
function showToast(message,type="success"){let toast=document.querySelector(".site-toast");if(!toast){toast=document.createElement("div");toast.className="site-toast";document.body.append(toast);}toast.textContent=message;toast.dataset.type=type;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),3200);}

document.querySelectorAll("[data-admin-view]").forEach(button=>button.addEventListener("click",()=>goTo(button.dataset.adminView)));
document.querySelector("#adminLogout").addEventListener("click",confirmLogout);
document.querySelector("#adminMenuToggle").addEventListener("click",event=>{const open=document.body.classList.toggle("admin-menu-open");event.currentTarget.setAttribute("aria-expanded",String(open));});
document.addEventListener("click",event=>{if(!event.target.closest(".more-menu"))document.querySelectorAll(".more-popover").forEach(menu=>menu.classList.add("hidden"));if(!event.target.closest(".size-dropdown"))root.querySelector("#sizeMenu")?.classList.add("hidden");if(!event.target.closest(".brand-combobox"))root.querySelector("#brandResults")?.classList.add("hidden");});
window.addEventListener("beforeunload",event=>{if(state.dirty){event.preventDefault();event.returnValue="";}});

onAuthStateChanged(auth,async user=>{
  if(!user){location.replace("cuenta.html?return=admin.html");return;}
  state.user=user;
  try{const snapshot=await getDoc(doc(db,"users",user.uid));state.profile=snapshot.exists()?snapshot.data():{};state.role=state.profile.role||"customer";}catch(error){console.error(error);state.role="customer";}
  try{sessionStorage.setItem(AUTH_HINT_KEY,JSON.stringify({signedIn:true,role:state.role,label:state.role==="admin"?"Gestionar catálogo":state.profile.name||user.displayName||"Mi cuenta"}));}catch{}
  state.ready=true;
  if(state.role!=="admin"){render();return;}
  render();
  state.stopProducts?.();state.stopProducts=onSnapshot(collection(db,"products"),snapshot=>{const products=snapshot.docs.map(item=>normalizeProduct({id:item.id,...item.data()})).sort((a,b)=>Number(b.createdOrder||0)-Number(a.createdOrder||0));const signature=productSignature(products),changed=!state.productsReady||signature!==state.productSignature;state.products=products;state.productSignature=signature;state.productsReady=true;writeProductCache(products);if(changed&&state.view!=="editor")render();},error=>{console.error(error);if(!state.productsReady)state.products=[];state.productsReady=true;if(state.view!=="editor")render();showToast(firestoreAdminMessage(error,"No se ha podido conectar con el catálogo de Firebase."),"error");});
  state.stopRequests?.();state.stopRequests=onSnapshot(collection(db,"requests"),snapshot=>{state.requests=snapshot.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>Number(b.createdAt?.seconds||0)-Number(a.createdAt?.seconds||0));updatePendingRequestCount();if(state.view==="requests")renderRequests();},error=>{console.error(error);state.requests=[];updatePendingRequestCount();if(state.view==="requests")renderRequests();showToast(firestoreAdminMessage(error,"No se han podido cargar las solicitudes."),"error");});
});
